# configuration related to pull request comments
coverage:
  range: 75..75 # coverage lower than 75 is red, higher than 75 is green

  status:
    project: # settings affecting project coverage
      default:
        target: 75 # auto % coverage target

    # do not run coverage on patch nor changes
    patch: false
