name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Create Release Asset
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Create ZIP for HACS
        run: |
          # Create the ZIP file directly from the hass_dyson directory
          # This ensures the zip extracts to the correct folder structure for HACS
          cd custom_components/hass_dyson
          zip -r ../../hass_dyson.zip .

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./hass_dyson.zip
          token: ${{ secrets.GITHUB_TOKEN }}